# docker-compose.yml

version: "2"
services:
  ms-minio:
    container_name: ms-minio
    restart: always
    image: minio/minio:RELEASE.2021-03-26T00-00-41Z
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: $MINIO_SECRET_KEY
    command: server /export
    volumes:
      - ../../src/MediaStudio.Minio/data:/export
      - ../../src/MediaStudio.Minio/config:/root/.minio  
    
  ms-postgres:
    container_name: ms-postgres
    image: postgres
    build:
      context: ../../src/MediaStudio.Postgres
      dockerfile: ../../docker/MediaStudio.Postgres.Dockerfile
    environment:
      POSTGES_DATA: /var/lib/postgres/data/pgdata
      POSTGRES_PASSWORD: $POSTGRES_SUPERUSER_PASSWORD      
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB_NAME: $POSTGRES_DB_NAME
      POSTGRES_DB_USER: $POSTGRES_DB_USER
      POSTGRES_DB_PASS: $POSTGRES_DB_PASS
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  mediastudio:
    container_name: mediastudio
    build:
      context: ../../src/
      dockerfile: ../docker/MediaStudio.Dockerfile
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - ms-postgres
      
  mediastudiocms:
    container_name: mediastudiocms
    build:
      context: ../../src/
      dockerfile: ../docker/MediaStudio.CMS.Dockerfile
    ports:
      - "8082:8082"
    restart: always
    depends_on:
      - ms-postgres